export const plans = [
  {
    id: 1,
    name: "Free",
    slug: "free",
    price: 0,
    currency: "VND",
    durationDays: null,
    dailyTestLimit: 5,
    aiExplanationLimit: 0,
    hasAiFeatures: false,
    hasWeaknessAnalysis: false,
    hasAdaptiveLearning: false,
    hasAdvancedDashboard: false,
    isActive: true,
  },
  {
    id: 2,
    name: "Premium Monthly",
    slug: "premium_monthly",
    price: 99000,
    currency: "VND",
    durationDays: 30,
    dailyTestLimit: null,
    aiExplanationLimit: null,
    hasAiFeatures: true,
    hasWeaknessAnalysis: true,
    hasAdaptiveLearning: true,
    hasAdvancedDashboard: true,
    isActive: true,
  },
  {
    id: 3,
    name: "Premium Quarterly",
    slug: "premium_quarterly",
    price: 249000,
    currency: "VND",
    durationDays: 90,
    dailyTestLimit: null,
    aiExplanationLimit: null,
    hasAiFeatures: true,
    hasWeaknessAnalysis: true,
    hasAdaptiveLearning: true,
    hasAdvancedDashboard: true,
    isActive: true,
  },
  {
    id: 4,
    name: "Premium Yearly",
    slug: "premium_yearly",
    price: 799000,
    currency: "VND",
    durationDays: 365,
    dailyTestLimit: null,
    aiExplanationLimit: null,
    hasAiFeatures: true,
    hasWeaknessAnalysis: true,
    hasAdaptiveLearning: true,
    hasAdvancedDashboard: true,
    isActive: true,
  },
];

export const questions = [
  {
    id: 1,
    skill: "listening",
    part: 1,
    questionType: "photograph",
    questionText: "What is happening in the picture?",
    imageUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript: "A woman is arranging documents on a desk.",
    explanation: "The photo shows office work with papers on a desk.",
    difficultyLevel: "easy",
    difficultyScore: 28,
    estimatedTimeSeconds: 35,
    isActive: true,
  },
  {
    id: 2,
    skill: "reading",
    part: 5,
    questionType: "incomplete_sentence",
    questionText: "The manager reviewed the report very ____ before the meeting.",
    explanation: "An adverb is needed to modify the verb reviewed.",
    grammarFormula: {
      title: "Word form",
      pattern: "Verb + adverb",
      example: "The manager reviewed the report carefully.",
    },
    vocabularyHints: [
      { word: "review", meaning: "xem xét / đánh giá", level: "Office" },
      { word: "carefully", meaning: "một cách cẩn thận", level: "Word form" },
    ],
    difficultyLevel: "easy",
    difficultyScore: 30,
    estimatedTimeSeconds: 30,
    isActive: true,
  },
  {
    id: 3,
    skill: "reading",
    part: 7,
    questionType: "reading_detail",
    questionText: "What should Ms. Tran bring to the registration desk?",
    passageText:
      "Dear Ms. Tran, Thank you for registering for the Regional Sales Conference. The opening session begins at 9:00 A.M. in Hall B. Please bring your confirmation email to the registration desk.",
    explanation: "The email asks her to bring the confirmation email.",
    grammarFormula: {
      title: "Reading evidence",
      pattern: "Question keyword -> scan passage -> match paraphrase",
      example: "bring to the registration desk -> confirmation email",
    },
    vocabularyHints: [
      { word: "registration desk", meaning: "bàn đăng ký", level: "Event" },
      { word: "confirmation email", meaning: "email xác nhận", level: "Email" },
    ],
    difficultyLevel: "medium",
    difficultyScore: 58,
    estimatedTimeSeconds: 60,
    isActive: true,
  },
];

export const answers = [
  { id: 101, questionId: 1, answerText: "A woman is arranging documents on a desk.", isCorrect: true, displayOrder: 1 },
  { id: 102, questionId: 1, answerText: "A man is painting a wall.", isCorrect: false, displayOrder: 2 },
  { id: 103, questionId: 1, answerText: "People are boarding a bus.", isCorrect: false, displayOrder: 3 },
  { id: 104, questionId: 1, answerText: "A chef is preparing food.", isCorrect: false, displayOrder: 4 },
  { id: 201, questionId: 2, answerText: "careful", isCorrect: false, displayOrder: 1 },
  { id: 202, questionId: 2, answerText: "carefully", isCorrect: true, displayOrder: 2 },
  { id: 203, questionId: 2, answerText: "care", isCorrect: false, displayOrder: 3 },
  { id: 204, questionId: 2, answerText: "caring", isCorrect: false, displayOrder: 4 },
  { id: 301, questionId: 3, answerText: "Her confirmation email", isCorrect: true, displayOrder: 1 },
  { id: 302, questionId: 3, answerText: "A printed invoice", isCorrect: false, displayOrder: 2 },
  { id: 303, questionId: 3, answerText: "A sales report", isCorrect: false, displayOrder: 3 },
  { id: 304, questionId: 3, answerText: "Her passport", isCorrect: false, displayOrder: 4 },
];
