import type { Answer, GrammarPoint, Question, QuestionGroup, Topic } from "./types";

export const topics: Topic[] = [
  { id: 1, name: "Business travel", skill: "both" },
  { id: 2, name: "Office communication", skill: "both" },
  { id: 3, name: "Restaurant", skill: "listening" },
  { id: 4, name: "Announcement", skill: "listening" },
  { id: 5, name: "Email", skill: "reading" },
  { id: 6, name: "Advertisement", skill: "reading" },
  { id: 7, name: "Schedule", skill: "both" },
  { id: 8, name: "Invoice", skill: "reading" },
];

export const grammarPoints: GrammarPoint[] = [
  { id: 1, name: "Part of speech", category: "Word form" },
  { id: 2, name: "Tenses", category: "Verb" },
  { id: 3, name: "Prepositions", category: "Structure" },
  { id: 4, name: "Conjunctions", category: "Structure" },
  { id: 5, name: "Relative clauses", category: "Clause" },
  { id: 6, name: "Passive voice", category: "Verb" },
];

export const questionGroups: QuestionGroup[] = [
  {
    id: 101,
    skill: "listening",
    part: 3,
    title: "Hotel reservation call",
    groupType: "conversation",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript:
      "Woman: Good morning, I'd like to confirm my room for Thursday night. Man: Certainly. I see a deluxe room under Nguyen. Woman: Could you add breakfast for two? Man: Of course, that will be included.",
  },
  {
    id: 102,
    skill: "listening",
    part: 4,
    title: "Train station announcement",
    groupType: "talk",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript:
      "Attention passengers. The 8:15 express train to Central City is delayed by twenty minutes due to track maintenance. Passengers may use platform four for the local service.",
  },
  {
    id: 201,
    skill: "reading",
    part: 6,
    title: "Office policy memo",
    groupType: "text_completion",
    passageText:
      "To all staff, the company will introduce a new remote work policy next month. Employees should submit their weekly plans to their managers by Friday afternoon.",
  },
  {
    id: 202,
    skill: "reading",
    part: 7,
    title: "Conference email",
    groupType: "reading_passage",
    passageText:
      "Dear Ms. Tran, Thank you for registering for the Regional Sales Conference. The opening session begins at 9:00 A.M. in Hall B. Please bring your confirmation email to the registration desk.",
  },
];

const baseExplanation =
  "The correct answer matches the context and avoids the distractor that sounds or looks similar.";

export const questions: Question[] = [
  {
    id: 1,
    skill: "listening",
    part: 1,
    questionType: "photograph",
    questionText: "What is happening in the picture?",
    imageUrl:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript: "A woman is arranging documents on a desk.",
    explanation: "The photo shows office work with papers on a desk.",
    topicId: 2,
    difficultyLevel: "easy",
    difficultyScore: 28,
    estimatedTimeSeconds: 35,
    correctRate: 78,
    attemptCount: 41,
    correctCount: 32,
    isActive: true,
  },
  {
    id: 2,
    skill: "listening",
    part: 1,
    questionType: "photograph",
    questionText: "Choose the best description of the image.",
    imageUrl:
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=900&q=80",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript: "Several people are seated around a conference table.",
    explanation: "The people are in a meeting, not walking or eating.",
    topicId: 2,
    difficultyLevel: "medium",
    difficultyScore: 48,
    estimatedTimeSeconds: 35,
    correctRate: 62,
    attemptCount: 52,
    correctCount: 32,
    isActive: true,
  },
  {
    id: 3,
    skill: "listening",
    part: 2,
    questionType: "question_response",
    questionText: "When will the report be ready?",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript: "When will the report be ready?",
    explanation: "The best response gives a time related to completion.",
    topicId: 2,
    difficultyLevel: "easy",
    difficultyScore: 32,
    estimatedTimeSeconds: 25,
    correctRate: 81,
    attemptCount: 61,
    correctCount: 49,
    isActive: true,
  },
  {
    id: 4,
    skill: "listening",
    part: 2,
    questionType: "question_response",
    questionText: "Who is responsible for ordering supplies?",
    audioUrl: "https://actions.google.com/sounds/v1/alarms/beep_short.ogg",
    transcript: "Who is responsible for ordering supplies?",
    explanation: "The correct response names a person responsible for the task.",
    topicId: 2,
    difficultyLevel: "medium",
    difficultyScore: 57,
    estimatedTimeSeconds: 25,
    correctRate: 58,
    attemptCount: 43,
    correctCount: 25,
    isActive: true,
  },
  {
    id: 5,
    questionGroupId: 101,
    skill: "listening",
    part: 3,
    questionType: "conversation_detail",
    questionText: "What does the woman want to confirm?",
    explanation: "She says she wants to confirm her room for Thursday night.",
    topicId: 1,
    difficultyLevel: "medium",
    difficultyScore: 54,
    estimatedTimeSeconds: 45,
    correctRate: 64,
    attemptCount: 33,
    correctCount: 21,
    isActive: true,
  },
  {
    id: 6,
    questionGroupId: 101,
    skill: "listening",
    part: 3,
    questionType: "conversation_detail",
    questionText: "What does the woman ask to add?",
    explanation: "She asks to add breakfast for two.",
    topicId: 1,
    difficultyLevel: "easy",
    difficultyScore: 37,
    estimatedTimeSeconds: 45,
    correctRate: 76,
    attemptCount: 29,
    correctCount: 22,
    isActive: true,
  },
  {
    id: 7,
    questionGroupId: 102,
    skill: "listening",
    part: 4,
    questionType: "announcement_detail",
    questionText: "Why is the train delayed?",
    explanation: "The announcement mentions track maintenance.",
    topicId: 4,
    difficultyLevel: "medium",
    difficultyScore: 60,
    estimatedTimeSeconds: 45,
    correctRate: 55,
    attemptCount: 37,
    correctCount: 20,
    isActive: true,
  },
  {
    id: 8,
    questionGroupId: 102,
    skill: "listening",
    part: 4,
    questionType: "announcement_inference",
    questionText: "Where should passengers go for the local service?",
    explanation: "Passengers may use platform four.",
    topicId: 7,
    difficultyLevel: "hard",
    difficultyScore: 76,
    estimatedTimeSeconds: 45,
    correctRate: 42,
    attemptCount: 31,
    correctCount: 13,
    isActive: true,
  },
  {
    id: 9,
    skill: "reading",
    part: 5,
    questionType: "incomplete_sentence",
    questionText: "The manager reviewed the report very ____ before the meeting.",
    explanation: "An adverb is needed to modify the verb reviewed.",
    topicId: 2,
    grammarPointId: 1,
    difficultyLevel: "easy",
    difficultyScore: 30,
    estimatedTimeSeconds: 30,
    correctRate: 79,
    attemptCount: 88,
    correctCount: 70,
    isActive: true,
  },
  {
    id: 10,
    skill: "reading",
    part: 5,
    questionType: "incomplete_sentence",
    questionText: "The invoices must be approved ____ the end of the week.",
    explanation: "The phrase is 'by the end of the week' for a deadline.",
    topicId: 8,
    grammarPointId: 3,
    difficultyLevel: "medium",
    difficultyScore: 52,
    estimatedTimeSeconds: 30,
    correctRate: 61,
    attemptCount: 72,
    correctCount: 44,
    isActive: true,
  },
  {
    id: 11,
    skill: "reading",
    part: 5,
    questionType: "incomplete_sentence",
    questionText: "The new software, ____ was installed yesterday, has improved productivity.",
    explanation: "A relative pronoun is needed to introduce the clause.",
    topicId: 2,
    grammarPointId: 5,
    difficultyLevel: "hard",
    difficultyScore: 78,
    estimatedTimeSeconds: 35,
    correctRate: 43,
    attemptCount: 58,
    correctCount: 25,
    isActive: true,
  },
  {
    id: 12,
    questionGroupId: 201,
    skill: "reading",
    part: 6,
    questionType: "text_completion",
    questionText: "Employees should submit ____ weekly plans by Friday.",
    explanation: "A possessive determiner is required before weekly plans.",
    topicId: 2,
    grammarPointId: 1,
    difficultyLevel: "medium",
    difficultyScore: 56,
    estimatedTimeSeconds: 50,
    correctRate: 59,
    attemptCount: 47,
    correctCount: 28,
    isActive: true,
  },
  {
    id: 13,
    questionGroupId: 201,
    skill: "reading",
    part: 6,
    questionType: "text_completion",
    questionText: "The policy will be introduced ____ month.",
    explanation: "The sentence refers to the following month.",
    topicId: 2,
    grammarPointId: 2,
    difficultyLevel: "easy",
    difficultyScore: 35,
    estimatedTimeSeconds: 50,
    correctRate: 75,
    attemptCount: 35,
    correctCount: 26,
    isActive: true,
  },
  {
    id: 14,
    questionGroupId: 202,
    skill: "reading",
    part: 7,
    questionType: "reading_detail",
    questionText: "What should Ms. Tran bring to the registration desk?",
    explanation: "The email asks her to bring the confirmation email.",
    topicId: 5,
    difficultyLevel: "medium",
    difficultyScore: 58,
    estimatedTimeSeconds: 60,
    correctRate: 56,
    attemptCount: 66,
    correctCount: 37,
    isActive: true,
  },
  {
    id: 15,
    questionGroupId: 202,
    skill: "reading",
    part: 7,
    questionType: "reading_detail",
    questionText: "Where does the opening session begin?",
    explanation: "The passage says the opening session begins in Hall B.",
    topicId: 7,
    difficultyLevel: "easy",
    difficultyScore: 38,
    estimatedTimeSeconds: 60,
    correctRate: 72,
    attemptCount: 62,
    correctCount: 45,
    isActive: true,
  },
  {
    id: 16,
    questionGroupId: 202,
    skill: "reading",
    part: 7,
    questionType: "reading_inference",
    questionText: "Why did Ms. Tran receive this email?",
    explanation: "She received it because she registered for the conference.",
    topicId: 5,
    difficultyLevel: "hard",
    difficultyScore: 82,
    estimatedTimeSeconds: 70,
    correctRate: 38,
    attemptCount: 44,
    correctCount: 17,
    isActive: true,
  },
];

export const answers: Answer[] = [
  { id: 101, questionId: 1, answerText: "A woman is arranging documents on a desk.", isCorrect: true, displayOrder: 1 },
  { id: 102, questionId: 1, answerText: "A man is painting a wall.", isCorrect: false, displayOrder: 2 },
  { id: 103, questionId: 1, answerText: "People are boarding a bus.", isCorrect: false, displayOrder: 3 },
  { id: 104, questionId: 1, answerText: "A chef is preparing food.", isCorrect: false, displayOrder: 4 },
  { id: 201, questionId: 2, answerText: "Several people are seated around a conference table.", isCorrect: true, displayOrder: 1 },
  { id: 202, questionId: 2, answerText: "The room is being painted.", isCorrect: false, displayOrder: 2 },
  { id: 203, questionId: 2, answerText: "A woman is walking alone outside.", isCorrect: false, displayOrder: 3 },
  { id: 204, questionId: 2, answerText: "The chairs have been stacked.", isCorrect: false, displayOrder: 4 },
  { id: 301, questionId: 3, answerText: "By three o'clock this afternoon.", isCorrect: true, displayOrder: 1 },
  { id: 302, questionId: 3, answerText: "It was on my desk.", isCorrect: false, displayOrder: 2 },
  { id: 303, questionId: 3, answerText: "The report was very detailed.", isCorrect: false, displayOrder: 3 },
  { id: 401, questionId: 4, answerText: "Mina from purchasing handles that.", isCorrect: true, displayOrder: 1 },
  { id: 402, questionId: 4, answerText: "They are in the storage room.", isCorrect: false, displayOrder: 2 },
  { id: 403, questionId: 4, answerText: "Every two weeks.", isCorrect: false, displayOrder: 3 },
  { id: 501, questionId: 5, answerText: "A hotel room", isCorrect: true, displayOrder: 1 },
  { id: 502, questionId: 5, answerText: "A flight reservation", isCorrect: false, displayOrder: 2 },
  { id: 503, questionId: 5, answerText: "A restaurant table", isCorrect: false, displayOrder: 3 },
  { id: 504, questionId: 5, answerText: "A meeting schedule", isCorrect: false, displayOrder: 4 },
  { id: 601, questionId: 6, answerText: "Breakfast for two", isCorrect: true, displayOrder: 1 },
  { id: 602, questionId: 6, answerText: "Airport pickup", isCorrect: false, displayOrder: 2 },
  { id: 603, questionId: 6, answerText: "A larger room", isCorrect: false, displayOrder: 3 },
  { id: 604, questionId: 6, answerText: "Late checkout", isCorrect: false, displayOrder: 4 },
  { id: 701, questionId: 7, answerText: "Track maintenance", isCorrect: true, displayOrder: 1 },
  { id: 702, questionId: 7, answerText: "Bad weather", isCorrect: false, displayOrder: 2 },
  { id: 703, questionId: 7, answerText: "Staff training", isCorrect: false, displayOrder: 3 },
  { id: 704, questionId: 7, answerText: "Ticket inspection", isCorrect: false, displayOrder: 4 },
  { id: 801, questionId: 8, answerText: "Platform four", isCorrect: true, displayOrder: 1 },
  { id: 802, questionId: 8, answerText: "Hall B", isCorrect: false, displayOrder: 2 },
  { id: 803, questionId: 8, answerText: "The ticket office", isCorrect: false, displayOrder: 3 },
  { id: 804, questionId: 8, answerText: "Gate nine", isCorrect: false, displayOrder: 4 },
  { id: 901, questionId: 9, answerText: "careful", isCorrect: false, displayOrder: 1 },
  { id: 902, questionId: 9, answerText: "carefully", isCorrect: true, displayOrder: 2 },
  { id: 903, questionId: 9, answerText: "care", isCorrect: false, displayOrder: 3 },
  { id: 904, questionId: 9, answerText: "caring", isCorrect: false, displayOrder: 4 },
  { id: 1001, questionId: 10, answerText: "by", isCorrect: true, displayOrder: 1 },
  { id: 1002, questionId: 10, answerText: "at", isCorrect: false, displayOrder: 2 },
  { id: 1003, questionId: 10, answerText: "for", isCorrect: false, displayOrder: 3 },
  { id: 1004, questionId: 10, answerText: "over", isCorrect: false, displayOrder: 4 },
  { id: 1101, questionId: 11, answerText: "who", isCorrect: false, displayOrder: 1 },
  { id: 1102, questionId: 11, answerText: "which", isCorrect: true, displayOrder: 2 },
  { id: 1103, questionId: 11, answerText: "where", isCorrect: false, displayOrder: 3 },
  { id: 1104, questionId: 11, answerText: "whose", isCorrect: false, displayOrder: 4 },
  { id: 1201, questionId: 12, answerText: "they", isCorrect: false, displayOrder: 1 },
  { id: 1202, questionId: 12, answerText: "their", isCorrect: true, displayOrder: 2 },
  { id: 1203, questionId: 12, answerText: "them", isCorrect: false, displayOrder: 3 },
  { id: 1204, questionId: 12, answerText: "theirs", isCorrect: false, displayOrder: 4 },
  { id: 1301, questionId: 13, answerText: "next", isCorrect: true, displayOrder: 1 },
  { id: 1302, questionId: 13, answerText: "last", isCorrect: false, displayOrder: 2 },
  { id: 1303, questionId: 13, answerText: "every", isCorrect: false, displayOrder: 3 },
  { id: 1304, questionId: 13, answerText: "some", isCorrect: false, displayOrder: 4 },
  { id: 1401, questionId: 14, answerText: "Her confirmation email", isCorrect: true, displayOrder: 1 },
  { id: 1402, questionId: 14, answerText: "A printed invoice", isCorrect: false, displayOrder: 2 },
  { id: 1403, questionId: 14, answerText: "A sales report", isCorrect: false, displayOrder: 3 },
  { id: 1404, questionId: 14, answerText: "Her passport", isCorrect: false, displayOrder: 4 },
  { id: 1501, questionId: 15, answerText: "Hall B", isCorrect: true, displayOrder: 1 },
  { id: 1502, questionId: 15, answerText: "Platform four", isCorrect: false, displayOrder: 2 },
  { id: 1503, questionId: 15, answerText: "Room 210", isCorrect: false, displayOrder: 3 },
  { id: 1504, questionId: 15, answerText: "The lobby cafe", isCorrect: false, displayOrder: 4 },
  { id: 1601, questionId: 16, answerText: "She registered for the conference.", isCorrect: true, displayOrder: 1 },
  { id: 1602, questionId: 16, answerText: "She missed a payment deadline.", isCorrect: false, displayOrder: 2 },
  { id: 1603, questionId: 16, answerText: "She requested a refund.", isCorrect: false, displayOrder: 3 },
  { id: 1604, questionId: 16, answerText: "She changed her flight.", isCorrect: false, displayOrder: 4 },
].map((answer) => ({ explanation: baseExplanation, ...answer }));
